service: pokemon-ai-serverless

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: ap-northeast-1
  websocketsApiName: pokemon-ai-websockets
  timeout: 30
  iamManagedPolicies:
    - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
plugins:
  - serverless-python-requirements
functions:
  hello:
    handler: handler.hello
  connectHandler:
    handler: handler.connect
    events:
      - websocket: $connect
  disconnectHandler:
    handler: handler.disconnect
    events:
      - websocket:
          route: $disconnect
  heartbeatHandler:
    handler: handler.heartbeat
    events:
      - websocket:
          route: heartbeat
  helloHandler:
    handler: handler.hello
    events:
      - websocket:
          route: hello
  defaultHandler:
    handler: handler.default
    events:
      - websocket:
          route: $default
resources:
  Resources:
    ConnectionId:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ConnectionId
        AttributeDefinitions:
          - AttributeName: player
            AttributeType: S
        KeySchema:
          - AttributeName: player
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
